bams:
    - {class: File, path: input_A.bam}
    - {class: File, path: input_Z.bam}
readgroups: ['@RG\tID:A\tPL:Illumina\tSM:test-sample-1', '@RG\tID:Z\tPL:Illumina\tSM:test-sample-1']
reference: GRCh38_full_analysis_set_plus_decoy_hla.fa